### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by n76** [Unlegacy-Android/android#1]
Probably something I have wrong in my setup or build command but I don't see it. Steps I took were:

```
> mkdir unlegacy
> cd unlegacy
> repo init -u https://github.com/Unlegacy-Android/android.git -b aosp-7.1
> repo sync
> . build/envsetup.sh
> lunch
> make installclean
> make clean
> make -j2 otapackage 2>&1 | tee ~/build.log
```

The target selected in "lunch" was 22 (aosp_tuna_userdebug)

The error message I am getting is

```
a/obj/SHARED_LIBRARIES/libbinder_intermediates/TextOutput.o: file is empty
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[ 34% 10107/29540] target thumb C++: libchrome <= external/libchrome/base/at_exit.cc
ninja: build stopped: subcommand failed.
build/core/ninja.mk:148: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

#### make failed to build some targets (21:34 (mm:ss)) ####
```

Any place I should be looking for clues?

(From a previously working OMAP4 ROM build environment I did have to upgrade Java and I thought the easiest way to do that was to upgrade from Ubuntu 14.04 LTS to 16.04 LTS as I could just to an apt-get for the needed packages in 16 but in 14 I would have needed to add some other repositories).

**Comment by apinela** [comment]
You must have some corrupted file on source code that promotes that.

btw, we suggest you to use our bugs.unlegacy-android.cf to report any issue related to UA/Devices that we support.
