### ISSUE TITLE
Total size of repo sync?

### ISSUE THREAD

**Issue by 0E800** [Unlegacy-Android/android#2]
Hello, I am trying to get the unlegacy 3.4 kernel source for the Nexus 7 grouper.
The intent is to add extra modules needed to be a compatible with Kali Nethunter.
Nethunter rolling release requires a 3.4 kernel.

I tried following your instructions to get the branch aosp-7.1 but the sync failed due to it exceeding the 30GBs I had remaining on the SSD.

What is the total size?

Is there a way I can just get the kernel source for a specific device without having to download everything?

**Comment by apinela** [comment]
You can fork the repo of grouper kernel here:
https://github.com/Unlegacy-Android/android_kernel_nvidia_tegra3
It is commonized with more devices.

You'll have a couple of branches, use the stable one.
We are welcome to new fixes/patches on our gerrit:
https://gerrit.unlegacy-android.org

PS: Those 30Gigs were coming from the full android/aosp project.

**Comment by 0E800** [comment]
Is this correct how I am compiling the tilapia/grouper kernel?
git clone https://github.com/Unlegacy-Android/android_kernel_nvidia_tegra3 -b stable
cd android_kernel_nvidia_tegra3
export ARCH=arm
export SUBARCH=arm
export CROSS_COMPILE=../toolchain/bin/arm-eabi-
make clean
make grouper_defconfig
make -j4

I think I am doing something wrong as whenever I copy the zImage to lazyflasher and install the kernel, I get boot loops.

I am thinking I need to set what build I am making , eg: Marshmellow , Nougat.

Any help would be greatly appreciated

**Comment by airend** [comment]
> whenever I copy the zImage to lazyflasher and install the kernel, I get boot loops.

When you say copy, do you mean replace kernel image inside boot image, or just write it as is? I'm not familiar with LazyFlasher, but you need to keep the rest of the Android boot image, if you only build zImage.

**Comment by 0E800** [comment]
Lazyflasher is a tool to help inject kernel binaries into the current boot image.

https://forum.xda-developers.com/android/software-hacking/zip-lazyflasher-tool-flashing-custom-t3549210/

Ultimately I decided to sync the repo.

To create a tilapia flashible UA ROM 8.1 
 I type :

. build/envsetup.sh
lunch ua_tilapia-userdebug
make otapackage

I also have a N7 2013 Flo, I can create a ROM using same method?

Is it possible to make just a boot.img of kernel?
