### ISSUE TITLE
web server www.unlegacy-android.org is down?

### ISSUE THREAD

**Issue by sten0** [Unlegacy-Android/android#4]
Hi!

Thank you so much for your work on Unlegacy, it's truly a life saver for everyone who can't afford a new and expensive tablet.  Unfortunately it seems the project server has been down for a while :-(

My Android 7.1 on Galaxy Tab 2 10.1 experiment failed, so I'd [edit: like to] to reflash with one of the following:

ua_espresso-4.4.4-20181228-1227.zip
md5sum: 9f4bf4614d01bc8e00e1c26f1ad78b53

or

ua_espresso-6.0.1-20190209-2244.zip 
md5sum: 2b29cdf397cc7326c6e948c95502ac49

I have a copy of ua_espresso-6.0.1-20180520-1936.zip for worst-case scenario, but it suffered from a terrible video overlay framebuffer corruption bug on this hardware.

If the project page is down permanently, then it would be nice to have the following added to a README in this repo:
https://webcache.googleusercontent.com/search?q=cache:QdN-tmIoXz4J:https://www.unlegacy-android.org/projects/unlegacy-android/wiki/Sync_ua

Regards,
Nicholas

**Comment by apinela** [comment]
Hi Nicholas,

We are sorry for the inconvenience, in a few days we will be back, our
server suffered an issue and we are doing our best to to solve it as fast
as we can.

Best regards,
UA Team

**Comment by sten0** [comment]
On Tue, Jun 11, 2019 at 05:00:39PM -0700, André Pinela wrote:
> Hi Nicholas,
> 
> We are sorry for the inconvenience, in a few days we will be back, our
> server suffered an issue and we are doing our best to to solve it as fast
> as we can.
> 
> Best regards,
> UA Team
> 

Hi André,

Thank you for your openness and quick reply :-)

P.S. I wonder if someone in your local Debian community (wherever that
might be) would want to help out with the server issue?

Cheers,
Nicholas

**Comment by sten0** [comment]
Yay!  You're back online :-)  Closing issue now
